
import 'package:get/get.dart';

class MyLocal implements Translations{
  @override
  Map<String, Map<String, String>> get keys =>{
    "ar" : {
      "splash_connect" : "...جاري الاتصال",
      "splash_alert_title" : "فشل الاتصال",
      "splash_alert_message" : "تأكد من ان جهازك متصل بالانترنت",
      "splash_alert_ok" : "حسنا",

      "choose_lang" : "اختر اللغه",

      "make_title" : "النوع",
      "make_search" : "ابحث هنا",
      "model_title" : "الطراز",

      "home_page1_title" : "الرئيسيه",
      "home_page2_title" : "المفضله",
      "home_page3_title" : "القائمه",
      "home_all" : "الكل",
      "home_sort_price_maxtomin" : "السعر من الاعلي الي الاقل",
      "home_sort_price_mintomax" : "السعر من الاقل الي الاعلي",
      "home_sort_kilo_maxtomin" : "الكيلوميتير من الاعلي الي الاقل",
      "home_sort_kilo_mintomax" : "الكيلوميتير من الاقل الي الاعلي",
      "home_sort_year_maxtomin" : "السنه من الاعلي الي الاقل",
      "home_sort_year_mintomax" : "السنه من الاقل الي الاعلي",
      "home_no_result" : "لايوجد نتائج للبحث",
      "home_favorite_empty" : "المفضله خاليه",
      "home_kilo" : "كيلو مترات",
      "home_year" : "السنه",

      "menu_setting" : "الاعدادات",
      "menu_change_lang" : "تغيير اللغه",
      "menu_location" : "موقعنا",
      "menu_exit" : "الخروج من التطبيق",
      "menu_alert_message" : "هل تود الخروج من التطبيق",
      "menu_alert_btn_cancel" : "الغاء",
      "menu_alert_btn_ok" : "موافق",

      "details_details" : "التفاصيل",
      "details_call" : "اتصل",
      "details_trim" : "الفئه",
      "details_year" : "السنه",
      "details_kilo" : "كيلومترات",
      "details_regional" : "المواصفات الاقليميه",
      "details_exterior" : "اللون الخارجي",
      "details_doors" : "عدد الابواب",
      "details_body_cond" : "الحاله",
      "details_mecha_cond" : "الحاله الميكانيكيه",
      "details_interior" : "اللون الداخلي",
      "details_horse" : "قوه الحصان",
      "details_body_type" : "نوع الجسم",
      "details_no_of" : "عدد الاسطوانات",
      "details_trans" : "نوع النقل",
      "details_fuel_type" : "نوع الوقود",
      "details_extras" : "اضافي",
      "details_steering" : "جهه القياده",
      "details_no" : "لايوجد",
      "details_posted" : "نشر في",

      "search_title" : "بحث",
      "search_make" : "اختر النوع",
      "search_model" : "اختر الطراز",
      "search_trim" : "اختر الفئه",
      "search_regional" : "اختر المواصفات الاقليميه",
      "search_price" : "السعر (بالدرهم)",
      "search_year" : "السنه",
      "search_kilo" : "كيلومترات",
      "search_min" : "من",
      "search_max" : "الي",
      "search_result" : "نتيجه البحث",
    },
    "en" : {
      "splash_connect" : "Connecting...",
      "splash_alert_title" : "Connection Faield",
      "splash_alert_message" : "Make sure your online",
      "splash_alert_ok" : "OK",

      "choose_lang" : "Choose Language",

      "make_title" : "Make",
      "make_search" : "Search here",
      "model_title" : "Model",

      "home_page1_title" : "Home",
      "home_page2_title" : "Favorite",
      "home_page3_title" : "Menu",
      "home_all" : "All",
      "home_sort_price_maxtomin" : "Price Highest to Lowest",
      "home_sort_price_mintomax" : "Price Lowest to Highest",
      "home_sort_kilo_maxtomin" : "Kilo Highest to Lowest",
      "home_sort_kilo_mintomax" : "Kilo Lowest to Highest",
      "home_sort_year_maxtomin" : "Year Highest to Lowest",
      "home_sort_year_mintomax" : "Year Lowest to Highest",
      "home_no_result" : "Oops! No results",
      "home_favorite_empty" : "Favorite is empty",
      "home_kilo" : "Kms",
      "home_year" : "Year",

      "menu_setting" : "Settings",
      "menu_change_lang" : "Change Language",
      "menu_location" : "Location",
      "menu_exit" : "Exit",
      "menu_alert_message" : "You sure you want exit",
      "menu_alert_btn_cancel" : "Cancel",
      "menu_alert_btn_ok" : "Ok",

      "details_details" : "Details",
      "details_call" : "Call",
      "details_trim" : "Trim",
      "details_year" : "Year",
      "details_kilo" : "Kilometers",
      "details_regional" : "Regional Specs",
      "details_exterior" : "Exterior Color",
      "details_doors" : "Doors",
      "details_body_cond" : "Body Condition",
      "details_mecha_cond" : "Mechanical Condition",
      "details_interior" : "Interior Color",
      "details_horse" : "Horse Power",
      "details_body_type" : "Body Type",
      "details_no_of" : "No.of Cylinders",
      "details_trans" : "Transmission Type",
      "details_fuel_type" : "Fuel Type",
      "details_extras" : "Extras",
      "details_steering" : "Steering Side",
      "details_no" : "No Extras",
      "details_posted" : "Posted On",

      "search_title" : "Search",
      "search_make" : "Choose Make",
      "search_model" : "Choose Model",
      "search_trim" : "Choose Trim",
      "search_regional" : "Choose Regional Specs",
      "search_price" : "Price (AED)",
      "search_year" : "Year",
      "search_kilo" : "Kilometers",
      "search_min" : "Min",
      "search_max" : "Max",
      "search_result" : "Search Result",
    }
  };

}